runtime: php55
api_version: 1

skip_files:
- ^.*node_modules(/.*)?
- .git

handlers:
# Serve PHP
- url: /(.+\.php)$
  script: \1

# Serve HTML
- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)
  expiration: "1h"

# Serve JS
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

# Serve CSS
- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

# Serve TXT
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

# Serve XML
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)
  expiration: "1h"

# Serve Images
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# Root Directory
- url: /
  script: /index.php
