runtime: php55
api_version: 1

skip_files:
- ^.*node_modules(/.*)?
- .git

handlers:
# Serve PHP
- url: /(.+\.php)$
  script: \1

# Serve JS
- url: /(.+\.js)$
  script: \1

# Serve CSS
- url: /(.+\.css)$
  script: \1

# Default
- url: /
  script: /index.php
